### ISSUE TITLE
Add help for IE

### ISSUE THREAD

**Issue by ai** [majo44/storeon-async-router#5]
Most of Storeon modules still work in IE.

Supporting IE is not mandatory, but you need help for users who support IE how to configure Babel.

**Comment by majo44** [comment]
The released package will contains es5 umd (common js) source which will be set as main in package.json, I hope is enough.

**Comment by ai** [comment]
Yeap, it is enough.

How much it increased the bundle size?

**Comment by majo44** [comment]
So es5/umd is twice bigger then es6/esm, it is not little but it is natural as it has to contains polycode for async/await, destructors, ect. but, as you probably already know, in my opinion the feature is es6/esm and I'm focused on  latest standard, also because it is much much much more simpler to define the dev workflow which is backward compatible, then to create solution which translate the code to latest standards. Any one who have to support IE11, know that nowadays have to establish the pipeline for backward compatibility.

Stereon itself can be a bit smaller with es6/esm syntax :)

**Comment by ai** [comment]
> So es5/umd is twice bigger then es6/esm

ES6 is not twice bigger. You got this size because of Babel is not really effective for the size and inserts a lot of unnecessary code.

If you will check Babel output you will see the problem parts (`for-of` for instance).

> Any one who have to support IE11, know that nowadays have to establish the pipeline for backward compatibility.

You can just add help to the docs. We do not need to support IE 11 in any Storeon projects.

In my experience, a lot of developers are not good at Babel. This is why help in the docs is required.

> Stereon itself can be a bit smaller with es6/esm syntax :)

ES modules are not finished yet. Most of the module's code does not work in browsers and Node.js. I am waiting for Node.js modules spec finalization and more practice about modules to provide a working solution, not just “modules for Babel”.

I already moved to ES6 in the project, which will not be used in IE 11 or Opera Mini. I will drop IE 11 when ES modules will be finished.

**Comment by majo44** [comment]
I wrote that " es5/umd is twice bigger then es6/esm" ... in case of my code, is 1.8 kB, not in general :) 
I'm not using Babel to translate code, as I do not like it :) and typescript compiler which I'm using on other hand for static type checking is totally enough for that task. 

I do not know what do you mean by:

> ES modules are not finished yet

Modules are part of living [official EcmaScript standard](https://www.ecma-international.org/ecma-262/6.0/#sec-modules). <script module> is a living [whatwg standard](https://html.spec.whatwg.org/multipage/webappapis.html#scripting-processing-model). [All browsers except IE11](https://caniuse.com/#search=es6%20modules) supports es modules.  So what is not finished ? 

> Most of the module's code does not work in browsers and Node.js. 

Firstly Node.js is a product of some company/organisation and is not a standard reference, and should never be considered as a reference. "Node.js modules spec" is only a spec of some particular product. On other hand, only way to change current situation, to solve problem which you mentioned, to change Node.js is ... pice by pice, module by module, library by library migrate to latest standards, please read this [thread](https://github.com/Polymer/lit-html/issues/516)  or/and read this [article](https://www.pikapkg.com/blog/pika-web-a-future-without-webpack). Who if not we are able to solve that problem. If we be able to create the critical mass the whole web will move to world without Babel, Typescript, Webpack, ect. 

Sorry Andy, please do not take this too personally, but I feels from your side a bit ignoranccy.   
Just look into the code, and you will have most of answers.
I'm 40+ old dinosaur software architect and from 15 years I'm working with front end, I remember the times when our main platform was IE6.  When you written "Tests are critical for any open source projects" I felt again as an teenager :)

**Comment by ai** [comment]
> Modules are part of living official EcmaScript standard. <script module> is a living whatwg standard. All browsers except IE11 supports es modules. So what is not finished ?

How to use them in real without bundler.

For instance, you have `import nanoid from ''nanoid` in your code. The browser will not understand it. This is why browsers are thinking about import maps right now.

> please read this thread or/and read this article. 

Yeap, these articles are the source of my current worries. I found that real usage of modules is too far away from spec. And pika looks like the first step. We need much more work to find how to use modules properly. To find the best practices and find the best ways to solve the round-trip problem.

> Sorry Andy, please do not take this too personally, but I feels from your side a bit ignoranccy.

Sorry, I just have too many open source projects to look deeper in every case 😓

**Comment by majo44** [comment]
> How to use them in real without bundler

So I will install nanoid-esm (1. thanks to [pikapck search](https://www.pikapkg.com/packages/?q=nanoid 2. why the imports are without extensions ?), then after install `@pikapkg/web` will produce automatically for me the browser friendly bundle in `web_modules` (it will be once per installation, not once per my code change), then in code I will `import ... from 'web_modules/nanoid-esm.js'`. It is for sure not perfect, but at least allows me to establish live reload development workflow without rebuild (watch) step. I know for this case I need also `bundling` step, but it changing and simplify the development workflow. There is no any configuration required, all is done automatically. So if I will have all dependencies with esm, for simple development I will need just npm, pika and static web server, nothing more needed, 0 configuration. This is how the example in [this repo](https://github.com/majo44/non-compromise-es6) works, (that example contains full workflow, with testing, linting, bundling for ie11, ...) .

> And pika looks like the first step. We need much more work to find how to use modules properly. 

Totally agree, but without first steps, also on our side, we will be not able to shift the stone. I understand the reason of [mapping proposal](https://github.com/WICG/import-maps), but personally I think this will just increase the complexity and will prolong the npm chaos. This will prolong "freedom" and not enforce standards :( What's more maps will not solve in package extension-less imports, so still we will need to use tools for solve the problem. But this is just my personal opinion, and I know that reality is such complex that this can be impossible.

> Sorry, I just have too many open source ...

Don't worry, I totally understand, I really appreciate your fantastic effort. Please know that within my organisation we are heavy using with success PostCSS and Autoprefixer. Thank you.

**Comment by ai** [comment]
> 2. why the imports are without extensions ?

Because is ESM specs you must pass a path to the file. It is required by browsers since they can’t send multiple HTTP requests to test `path + '/index.js', path + '/index.json', path + '.js`

> then after install @pikapkg/web will produce automatically for me the browser friendly bundle in web_modules

Does pika solve round-trip problem (they avoid solving it in first versions, do they change it)?

I mean a chain of request: `app.js` → `./web_modules/liba.js` → `./web_modules/llibb.js` (when app imports `liba` and `liba` imports `libb`). Because we need 100-500ms for every request round-trip, we will have 1.5 s delay even on a high-speed 4G connection.

One of the possible solutions is using `<link rel="preload"` to ask browser start to download `./web_modules/liba.js` and `./web_modules/llibb.js` at the same moment when it will see `app.js` link. But we need bundler to generate dependencies map and write `link preload` to HTML.

**Comment by majo44** [comment]
Pika is not solving such problem, they are bundling the package (tree under single entry point). 

Indeed to  solve that kind of problem we can force to preload or prefetch for lazy loaded stuff, or we can use .... bundler tool like webpack, and I think, because of tree shaking, chunking, minification, obfuscation, ect.  for building super optimized, safe production builds, we will need such tool.

BUT
Production optimization step should be optional, we should be able to add in any point of time, should never have an impact on my code. That tool should be never be assumed as my dependency, I should be able to replace it in any point of time, or even to remove it at all if I will see that is not required anymore. No more `import "sass!./...."` as this is tool specific. 

For the prototyping, experimenting, development phase we do not need to solve that problem. More details I already described you here: https://github.com/storeon/storeon/issues/20#issuecomment-486459276

**Comment by majo44** [comment]
P.S.
Now I want to add some samples to this library, and most simple solution for that will be just put few html files, one per sample, with short inline sample code within script tag,  where I will be able just refer deps by cdn like : https://unpkg.com/storeon-async-router@0.1.0/index.js?module but I'm not able as storeon is not contains esm :(

**Comment by ai** [comment]
All my experience told me that giving people CDN URL will force them to use CDN in production websites. It will have a dramatical effect on web performance.

**Comment by majo44** [comment]
Reference to storen 178 B (+ eg. 1 kB router + 3 kB of lit-html/element) via CDN is fantastic result in compassion to super optimized >= 1,5 MB of React/Angular stack :) Switch to such stack will have "dramatical positive effect on web performance". :)

But seriously, If someone will want to shoot own leg, even with my best intentions, will be able to do that. And again, is nothing wrong to start with CDN and after some time change to super efficient solution, if there will be the reason for that.

**Comment by majo44** [comment]
Closing as probably all what is needed is done, released package contains es5/commonjs code which can be handled as from any other package by the any bundler.
